# Generated by Django 3.1 on 2020-08-11 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuotedSecurities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_data', models.DateField()),
                ('secid', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=765)),
                ('isin', models.CharField(max_length=765)),
                ('reg_number', models.CharField(blank=True, max_length=189, null=True)),
                ('main_board_id', models.CharField(blank=True, max_length=12, null=True)),
                ('list_level', models.CharField(blank=True, max_length=6, null=True)),
                ('quoted', models.BooleanField()),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_data', models.DateField()),
                ('close', models.FloatField(null=True)),
                ('name', models.CharField(max_length=765)),
                ('board_id', models.CharField(max_length=12, null=True)),
                ('secid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stonks.quotedsecurities')),
            ],
        ),
    ]
